services:
  users-service:
    container_name: gochat_users
    build: ./users-service
    ports:
      - 8002:8002
    env_file:
      - ./users-service/.env
    command: sh -c "
      ./migrate -path ./schema -database  postgres://postgres:postgres@db_users:5432/users?sslmode=disable up
      && ./main"
    depends_on:
      - auth

  db_users:
    container_name: gochat_auth_db
    image: postgres:16.2
    environment:
      - POSTGRES_DB=users
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - users_db:/var/lib/postgresql/data

volumes:
  users_db:
